### PR TITLE
WIP: 21w37a

### PR DESCRIPTION
**Pull request by modmuss50**
Broken, made a PR for safe keeping/discussion.

### CODE REVIEW

**Comment by ghost** [comment]
For those wondering why this is WIP, Mojang has started using records in their code however Proguard is stripping the record component from them meaning they need to be rebuilt, this may be fixed on mojangs end in future snapshots but is not guaranteed. 

Rebuilding records is relatively easy so this shouldn't be WIP for too long.

**Comment by liach** [comment]
so it's just the stripping of the recordcomponent attribute, i assume?

**Comment by modmuss50** [comment]
It also looks like the records getter methods dont always match the field names.

**Comment by gudenau** [comment]
Let me get this right, it is taking a class that looks like this (javac output, not source):
```Java
public final record class Record(int value){
    private final int value;

    public Record(int value){
        this.value = value;
    }

    public int value(){
        return value;
    }

    public String toString(){
        // invoke dynamic call
    }

    public int hashCode(){
        // invoke dynamic call
    }

    public boolean equals(Object other){
        // invoke dynamic call
    }
}
```
into
```Java
public final class Record{
    private final int value;

    public Record(int value){
        this.value = value;
    }

    public int value(){
        return value;
    }

    public String toString(){
        // invoke dynamic call
    }

    public int hashCode(){
        // invoke dynamic call
    }

    public boolean equals(Object other){
        // invoke dynamic call
    }
}
```

**Comment by ghost** [comment]
Mostly, the parent class is still java's inbuilt `Record` class and according to modmuss the method name doesn't always match up with the field name. e.g. possibly like:
```java
public int a() {
  return this.b;
}
```

For an actual example check out class `ahf`.

**Comment by gudenau** [comment]
I forgot about the `Record` class, I haven't played with them too much. So I suppose the getters should be named after the fields? It is going to be annoying to update the invoke dynamic calls.

**Comment by liach** [comment]
An interesting feature is that when proguarded records are inspected by reflection, **they are not records**.

Use this [`Test.java`](https://gist.github.com/a77f848599c549a995551d3df7ca07fa), and run it with
```sh
javac Test.java
java -cp "./;./21w37a-server.jar" Test
```
Assuming your server jar is `21w37a-server.jar` in the same directory as the `Test.java` file.

Interesting result is that running this yields `false` and `null`, i.e. since the `Record` attribute is gone, it is no longer a record. And by checking, it appears that [`j.l.r.ObjectMethods`](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/runtime/ObjectMethods.java) which record object methods depend on indeed do not require the lookup lookupClass (caller) to be records.

---

> according to modmuss the method name doesn't always match up with the field name

@modmuss50 mind give an example by obf name? I am more than glad to check.

---

After all, record is more like another enum. Their public name is actually quite visible: They are passed to bootstrap methods from constant pool entries in an [API designated format](https://github.com/openjdk/jdk/blob/74ffe12267cb3ae63072a06f50083fd0352d8049/src/java.base/share/classes/java/lang/runtime/ObjectMethods.java#L320-L322), which is not likely to change without prior notices (part of JDK's public API).

**Comment by liach** [comment]
Also, if possible, I wish you can match from experimental snapshots. It seems to me that this is way closer to exp snapshots than 1.17.1, from which you are matching.

**Comment by modmuss50** [comment]
> mind give an example by obf name? I am more than glad to check.

`ahf`

> way closer to exp snapshots

It was confirmed to not be based off the exp snapshots, I do want to try and still save the yarn names, will prob require using 2 matches. Not sure the record issue is the current blocker.

**Comment by liach** [comment]
@modmuss50 Hmm, what exactly are you trying to accomplish with intermediaries here? I would suggest just using regular intermediary generation to generate dissociated names for the fields and the getters. Do we currently have some problems on that part?

After all, these will get inferred names like enums with easy bootstrap method scans; but compared to enums, we are actually more free to name these fields and methods separately, as in the game distribution, the record attribute is gone, class is not record, so those record-specific benefits and restrictions are gone, too.

**Comment by liach** [comment]
Fyi discord now doesn't let me create burner accounts that can view stuff (cannot talk) for fabric discord. I don't know why, but this is probably confirms my tendency to avoid discord. Please dump as much information here as possible; thanks!

**Comment by modmuss50** [comment]
Player is working on fixing the intermediary gen, its goes against some of the plans we we already had in place to support records under the assumption that they would have the same field and method names. (I wouldnt call it a waste of effort as these changes mostly go on top of that).

My hope is that tiny remapper (or even better mojang) will put back the record component atrributes.

Auto naming these should be possible but we will still want to be able to overwrite them with our own names, I have started on some enigma changes: https://github.com/FabricMC/Enigma/pull/428 to handle the split method/field naming enough for us to use in it in yarn. More work will need to be done for it to understand what method corresponds to each field. This can come at a later date.

**Comment by liach** [comment]
> More work will need to be done for it to understand what method corresponds to each field.

This concept ain't quite right. Records only require there to be methods corresponding to the record component names and having a getter descriptor (add `()` in front of the field desc). See this example:

```java
import java.util.*;

public record Recty(int a, int b) {
	@Override
	public int b() {
		return a * 2;
	}

	public static void main(String... args) {
		var rec = new Recty(15, 6);
		System.out.println(rec.b + " " + rec.b());
	}
}
```
Here `b()` is nominally a getter, yet it isn't; hence I do not recommend requiring correspondences, especially given that we are actually free to violate record assumptions because they are **not** records in the distributed jars and at runtime, as seen in the example above.

Imo, since they are not records, trying to restore them as records offer no real benefit, probably except the potential record pattern matching that's upcoming only in java 18. But I don't know how that feature will work with record attributes yet :disappointed:

**Comment by Player3324** [comment]
> Fyi discord now doesn't let me create burner accounts that can view stuff (cannot talk) for fabric discord. I don't know why, but this is probably confirms my tendency to avoid discord. Please dump as much information here as possible; thanks!

if you tried within 5 min of joining that's normal anti-spam protection affecting everyone

**Comment by liach** [comment]
> > Fyi discord now doesn't let me create burner accounts that can view stuff (cannot talk) for fabric discord. I don't know why, but this is probably confirms my tendency to avoid discord. Please dump as much information here as possible; thanks!
> 
> if you tried within 5 min of joining that's normal anti-spam protection affecting everyone

Doesn't work :confused:, still
image

**Comment by gudenau** [comment]
Maybe a preprocessor pass should be added for things like this?

**Comment by apple502j** [comment]
Oof, that's why I couldn't join The Snapshot Mapping Speedrun:tm:

> It was confirmed to not be based off the exp snapshots

Perhaps it's based on older exp snapshots, like exp6? Elytra change wasn't in this snapshot, so maybe that's the case.

**Comment by liach** [comment]
@modmuss50 Just curious, will we track counts of record components as seen in #24 or no?

**Comment by modmuss50** [comment]
#24 is what we will be going with. This PR was mainly to just not loose what I had done.

**Comment by Player3324** [comment]
They are dedicated intermediary names (comp_123 instead of field_123/method_123), not just counts. The idea behind them is to make it easy to identify components for other tools since that can be really hard otherwise.

**Pull request closed without merging**
