### PR TITLE
19w42a

### PR DESCRIPTION
**Pull request by liach**
Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by natanfudge** [comment]
wat dis?

**Comment by natanfudge** [comment]
@modmuss50 confirmed replaced by @liach

**Comment by liach** [comment]
Well I need to practice so that someone knows how to carry on once modmuss and asie are both away

**Comment by natanfudge** [comment]
Player?

**Comment by natanfudge** [comment]
I, for one, welcome our new liach overlord though.

**Comment by modmuss50** [comment]
I will push mine, and then we can diff them to see. Thanks for trying though possibly down the line I may look into using it.

**Comment by liach** [comment]
A diff has been created and is available at https://gist.github.com/ac48ce46407c4ff79cdf365f82953ce0

**Comment by natanfudge** [comment]
Is this a lot of conflicts? It seems like it.

**Comment by liach** [comment]
modmuss happens to match like 3 more methods than I did, and there is a class matched differently

**Comment by liach** [comment]
Or alternatively, look at this: https://github.com/FabricMC/intermediary/compare/master..liachmodded:19w42a?expand=1

**Pull request closed without merging**
