### PR TITLE
Add mc version info to the jar manifest.

### PR DESCRIPTION
**Pull request by modmuss50**
This change uses Fabric loader to include the computed semver compatbile version info into the intermediary jar manifest. It also now uses mapping-io to handle the tiny v1 -> v2 conversion.

1.18-rc4 looks like:
```
Manifest-Version: 1.0
Game-Id: minecraft
Game-Version: 1.18-rc.4
Minecraft-Version-Id: 1.18-rc4
Minecraft-Version-Name: 1.18 Release Candidate 4
Build-Time: 2021-12-29T12:26:22.842350900Z
```

Depends on https://github.com/FabricMC/fabric-loader/pull/575 and testing, the plan is to re-release the full back catelog of intermediary jars with this updated infomation.

### CODE REVIEW

**Comment by modmuss50** [comment]
Now also publishes a json file such as:

```json
{
    "normalized_minecraft_version": "1.17-alpha.21.17.a",
    "minecraft_version_id": "21w17a",
    "minecraft_version_name": "21w17a"
}
```

**Review by thecatcore — APPROVED** [review]

**Comment by thecatcore** [comment]
Any progress on this? Loader pr is merged already.

**Comment by modmuss50** [comment]
The plan is to release the loader changes soon, just need to do some more testing. Once released this PR can progress. 👍

**Comment by liach** [comment]
@modmuss50 What's the current status?

**Comment by modmuss50** [comment]
This approach is no longer going to work going forward as minecraft no longer includes a target version. I think we are now going to need to manually specify the version in intermediary for loader to read.

**Pull request closed without merging**
